package com.jfd.stockrecipesmanagement.gui;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import org.kordamp.ikonli.materialdesign2.MaterialDesignA;
import org.kordamp.ikonli.materialdesign2.MaterialDesignS;
import org.kordamp.ikonli.swing.FontIcon;


/**
 *
 * @author javie
 */

public class MainMenu extends javax.swing.JFrame {
    private CardLayout card;    
    private List<String> listaOrdenCompra = new ArrayList<String>();
            
    public MainMenu() {
        initComponents();
        FontIcon iconPath = FontIcon.of(MaterialDesignS.SUBDIRECTORY_ARROW_RIGHT);
        iconPath.setIconSize(15);
        txtButtToMainMenu.setIcon(iconPath);
        
        FontIcon iconrightarrow = FontIcon.of(MaterialDesignA.ARROW_RIGHT_CIRCLE_OUTLINE);
        iconrightarrow.setIconSize(30);
        txtIconNextArrow.setIcon(iconrightarrow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        cardPanelMainMenu = new javax.swing.JPanel();
        card1CentralPanelContent = new javax.swing.JPanel();
        txtButtNuevoPedido = new javax.swing.JLabel();
        txtButtConsInvent = new javax.swing.JLabel();
        txtButtNvaOrdenC = new javax.swing.JLabel();
        txtButtBajaStock = new javax.swing.JLabel();
        txtBienvenido = new javax.swing.JLabel();
        cardPanelNvaOrdC1 = new javax.swing.JPanel();
        card1CentralPanelContent1 = new javax.swing.JPanel();
        txtButtToMainMenu = new javax.swing.JLabel();
        txtPathOrdCDetalles = new javax.swing.JLabel();
        txtIconNextArrow = new javax.swing.JLabel();
        textFMatPrimaCateg = new javax.swing.JTextField();
        labelMatPrimaCateg = new javax.swing.JLabel();
        labelMatPrimaSubcateg = new javax.swing.JLabel();
        labelMatPrimaMarca = new javax.swing.JLabel();
        labelMatPrimaTipo = new javax.swing.JLabel();
        labelMatPrimaCantid = new javax.swing.JLabel();
        labelMatPrimaUnidades = new javax.swing.JLabel();
        textFMatPrimaSubcateg = new javax.swing.JTextField();
        textFMatPrimaMarca = new javax.swing.JTextField();
        textFMatPrimaTipo = new javax.swing.JTextField();
        textFMatPrimaCantid = new javax.swing.JTextField();
        panelListOrdCompra = new javax.swing.JPanel();
        listOrdenCompra = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        comboBoxUnidades = new javax.swing.JComboBox<>();
        labelButtCargarElemento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelButtBorrarElemento = new javax.swing.JLabel();
        txtTitleOrdCompra = new javax.swing.JLabel();
        txtSubtitleDetalleProduct = new javax.swing.JLabel();
        txtSubtitleObservaciones = new javax.swing.JLabel();
        txtSubtitleGenPDF = new javax.swing.JLabel();
        txtSubtitleConfirmarCompra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1020, 584));
        background.setLayout(new java.awt.CardLayout());

        cardPanelMainMenu.setBackground(new java.awt.Color(25, 118, 211));

        card1CentralPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        txtButtNuevoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtButtNuevoPedido.setForeground(new java.awt.Color(25, 118, 211));
        txtButtNuevoPedido.setText("Nuevo Pedido");
        txtButtNuevoPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButtNuevoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtButtNuevoPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtButtNuevoPedidoMouseExited(evt);
            }
        });

        txtButtConsInvent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtButtConsInvent.setForeground(new java.awt.Color(25, 118, 211));
        txtButtConsInvent.setText("Consultar Inventario");
        txtButtConsInvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButtConsInvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtButtConsInventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtButtConsInventMouseExited(evt);
            }
        });

        txtButtNvaOrdenC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtButtNvaOrdenC.setForeground(new java.awt.Color(25, 118, 211));
        txtButtNvaOrdenC.setText("Nueva Orden de Compra");
        txtButtNvaOrdenC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButtNvaOrdenC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtButtNvaOrdenCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtButtNvaOrdenCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtButtNvaOrdenCMouseExited(evt);
            }
        });

        txtButtBajaStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtButtBajaStock.setForeground(new java.awt.Color(25, 118, 211));
        txtButtBajaStock.setText("Baja de Stock");
        txtButtBajaStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButtBajaStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtButtBajaStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtButtBajaStockMouseExited(evt);
            }
        });

        txtBienvenido.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        txtBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBienvenido.setText("Bienvenido");

        javax.swing.GroupLayout card1CentralPanelContentLayout = new javax.swing.GroupLayout(card1CentralPanelContent);
        card1CentralPanelContent.setLayout(card1CentralPanelContentLayout);
        card1CentralPanelContentLayout.setHorizontalGroup(
            card1CentralPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1CentralPanelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card1CentralPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtButtConsInvent)
                    .addComponent(txtButtNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButtNvaOrdenC)
                    .addComponent(txtButtBajaStock)
                    .addComponent(txtBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card1CentralPanelContentLayout.setVerticalGroup(
            card1CentralPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1CentralPanelContentLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(txtBienvenido)
                .addGap(44, 44, 44)
                .addComponent(txtButtNuevoPedido)
                .addGap(18, 18, 18)
                .addComponent(txtButtConsInvent)
                .addGap(18, 18, 18)
                .addComponent(txtButtNvaOrdenC)
                .addGap(18, 18, 18)
                .addComponent(txtButtBajaStock)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardPanelMainMenuLayout = new javax.swing.GroupLayout(cardPanelMainMenu);
        cardPanelMainMenu.setLayout(cardPanelMainMenuLayout);
        cardPanelMainMenuLayout.setHorizontalGroup(
            cardPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanelMainMenuLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(card1CentralPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPanelMainMenuLayout.setVerticalGroup(
            cardPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card1CentralPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(cardPanelMainMenu, "card1");

        cardPanelNvaOrdC1.setBackground(new java.awt.Color(25, 118, 211));

        card1CentralPanelContent1.setBackground(new java.awt.Color(255, 255, 255));

        txtButtToMainMenu.setForeground(new java.awt.Color(25, 118, 211));
        txtButtToMainMenu.setText("Menú Principal");
        txtButtToMainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtButtToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtButtToMainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtButtToMainMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtButtToMainMenuMouseExited(evt);
            }
        });

        txtPathOrdCDetalles.setText("/ Nueva orden de Compra / Detalles de Productos");

        txtIconNextArrow.setText(" ");

        textFMatPrimaCateg.setText("-");
        textFMatPrimaCateg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFMatPrimaCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFMatPrimaCategActionPerformed(evt);
            }
        });

        labelMatPrimaCateg.setText("Categoría");

        labelMatPrimaSubcateg.setText("Subcategoría");

        labelMatPrimaMarca.setText("Marca");

        labelMatPrimaTipo.setText("Tipo");

        labelMatPrimaCantid.setText("Cantidad");

        labelMatPrimaUnidades.setText("Unidades");

        textFMatPrimaSubcateg.setText("-");
        textFMatPrimaSubcateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFMatPrimaSubcategActionPerformed(evt);
            }
        });

        textFMatPrimaMarca.setText("-");

        textFMatPrimaTipo.setText("-");
        textFMatPrimaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFMatPrimaTipoActionPerformed(evt);
            }
        });

        textFMatPrimaCantid.setText("-");

        panelListOrdCompra.setLayout(new java.awt.BorderLayout());

        jList2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "sus productos aparecerán aquí" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionBackground(new java.awt.Color(25, 118, 211));
        jList2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jList2.setVisibleRowCount(15);
        listOrdenCompra.setViewportView(jList2);

        panelListOrdCompra.add(listOrdenCompra, java.awt.BorderLayout.CENTER);

        comboBoxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "kg", "g", "l", "ml", "u." }));
        comboBoxUnidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboBoxUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUnidadesActionPerformed(evt);
            }
        });

        labelButtCargarElemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelButtCargarElemento.setForeground(new java.awt.Color(0, 0, 255));
        labelButtCargarElemento.setText("Cargar Elemento");
        labelButtCargarElemento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelButtCargarElemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelButtCargarElemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtCargarElementoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelButtBorrarElemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelButtBorrarElemento.setForeground(new java.awt.Color(0, 0, 255));
        labelButtBorrarElemento.setText("Borrar Elemento Seleccionado");
        labelButtBorrarElemento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelButtBorrarElemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelButtBorrarElemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtBorrarElementoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(labelButtBorrarElemento)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelButtBorrarElemento)
        );

        javax.swing.GroupLayout card1CentralPanelContent1Layout = new javax.swing.GroupLayout(card1CentralPanelContent1);
        card1CentralPanelContent1.setLayout(card1CentralPanelContent1Layout);
        card1CentralPanelContent1Layout.setHorizontalGroup(
            card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtButtToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPathOrdCDetalles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1CentralPanelContent1Layout.createSequentialGroup()
                .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMatPrimaCateg)
                            .addComponent(labelMatPrimaSubcateg)
                            .addComponent(labelMatPrimaMarca)
                            .addComponent(labelMatPrimaCantid)
                            .addComponent(labelMatPrimaTipo)
                            .addComponent(labelMatPrimaUnidades))
                        .addGap(111, 111, 111)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFMatPrimaTipo)
                            .addComponent(textFMatPrimaCantid)
                            .addComponent(comboBoxUnidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFMatPrimaSubcateg)
                            .addComponent(textFMatPrimaCateg, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(textFMatPrimaMarca)))
                    .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(labelButtCargarElemento)))
                .addGap(16, 16, 16)
                .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListOrdCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1CentralPanelContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIconNextArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        card1CentralPanelContent1Layout.setVerticalGroup(
            card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtButtToMainMenu)
                            .addComponent(txtPathOrdCDetalles))
                        .addGap(81, 81, 81)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFMatPrimaCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMatPrimaCateg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatPrimaSubcateg)
                            .addComponent(textFMatPrimaSubcateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatPrimaMarca)
                            .addComponent(textFMatPrimaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatPrimaTipo)
                            .addComponent(textFMatPrimaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatPrimaCantid)
                            .addComponent(textFMatPrimaCantid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card1CentralPanelContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMatPrimaUnidades))
                        .addGap(18, 18, 18)
                        .addComponent(labelButtCargarElemento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(card1CentralPanelContent1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(panelListOrdCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(txtIconNextArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        txtTitleOrdCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitleOrdCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtTitleOrdCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitleOrdCompra.setText("Orden Compra");

        txtSubtitleDetalleProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSubtitleDetalleProduct.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitleDetalleProduct.setText("Detalle de Productos");

        txtSubtitleObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitleObservaciones.setText("Observaciones");

        txtSubtitleGenPDF.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitleGenPDF.setText("Generar PDF");

        txtSubtitleConfirmarCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitleConfirmarCompra.setText("Confirmar Compra Realizada");

        javax.swing.GroupLayout cardPanelNvaOrdC1Layout = new javax.swing.GroupLayout(cardPanelNvaOrdC1);
        cardPanelNvaOrdC1.setLayout(cardPanelNvaOrdC1Layout);
        cardPanelNvaOrdC1Layout.setHorizontalGroup(
            cardPanelNvaOrdC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanelNvaOrdC1Layout.createSequentialGroup()
                .addGroup(cardPanelNvaOrdC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardPanelNvaOrdC1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtTitleOrdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardPanelNvaOrdC1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(cardPanelNvaOrdC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubtitleGenPDF)
                            .addComponent(txtSubtitleConfirmarCompra)
                            .addComponent(txtSubtitleObservaciones)
                            .addComponent(txtSubtitleDetalleProduct))))
                .addGap(14, 14, 14)
                .addComponent(card1CentralPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPanelNvaOrdC1Layout.setVerticalGroup(
            cardPanelNvaOrdC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card1CentralPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardPanelNvaOrdC1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitleOrdCompra)
                .addGap(54, 54, 54)
                .addComponent(txtSubtitleDetalleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtSubtitleObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtSubtitleGenPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtSubtitleConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(cardPanelNvaOrdC1, "card2");

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//-------------------MENU PRINCIPAL-----------------------------------------------------------
    private void txtButtNuevoPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtNuevoPedidoMouseEntered
        // TODO add your handling code here:
        txtButtNuevoPedido.setForeground(new java.awt.Color(23, 132, 21));
    }//GEN-LAST:event_txtButtNuevoPedidoMouseEntered

    private void txtButtNuevoPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtNuevoPedidoMouseExited
        // TODO add your handling code here:
        txtButtNuevoPedido.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_txtButtNuevoPedidoMouseExited

    private void txtButtConsInventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtConsInventMouseEntered
        // TODO add your handling code here:
        txtButtConsInvent.setForeground(new java.awt.Color(23, 132, 21));
    }//GEN-LAST:event_txtButtConsInventMouseEntered

    private void txtButtConsInventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtConsInventMouseExited
        // TODO add your handling code here:
        txtButtConsInvent.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_txtButtConsInventMouseExited

    private void txtButtNvaOrdenCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtNvaOrdenCMouseEntered
        // TODO add your handling code here:
        txtButtNvaOrdenC.setForeground(new java.awt.Color(23, 132, 21));
    }//GEN-LAST:event_txtButtNvaOrdenCMouseEntered

    private void txtButtNvaOrdenCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtNvaOrdenCMouseExited
        // TODO add your handling code here:
        txtButtNvaOrdenC.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_txtButtNvaOrdenCMouseExited

    private void txtButtBajaStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtBajaStockMouseEntered
        // TODO add your handling code here:
        txtButtBajaStock.setForeground(new java.awt.Color(23, 132, 21));
    }//GEN-LAST:event_txtButtBajaStockMouseEntered

    private void txtButtBajaStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtBajaStockMouseExited
        // TODO add your handling code here:
        txtButtBajaStock.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_txtButtBajaStockMouseExited

    private void txtButtNvaOrdenCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtNvaOrdenCMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) this.background.getLayout();
        card.show(background, "card2");
    }//GEN-LAST:event_txtButtNvaOrdenCMouseClicked

//---------------Nueva Orden de Compra ------------------------------------------------------------------------
    private void txtButtToMainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtToMainMenuMouseEntered
        // TODO add your handling code here:
        txtButtBajaStock.setForeground(new java.awt.Color(23, 132, 21));
    }//GEN-LAST:event_txtButtToMainMenuMouseEntered

    private void txtButtToMainMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtToMainMenuMouseExited
        // TODO add your handling code here:
        txtButtBajaStock.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_txtButtToMainMenuMouseExited

    private void txtButtToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtButtToMainMenuMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) this.background.getLayout();
        card.show(background, "card1");
    }//GEN-LAST:event_txtButtToMainMenuMouseClicked

    private void textFMatPrimaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFMatPrimaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFMatPrimaTipoActionPerformed

    private void comboBoxUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxUnidadesActionPerformed

    private void textFMatPrimaCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFMatPrimaCategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFMatPrimaCategActionPerformed

    private void textFMatPrimaSubcategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFMatPrimaSubcategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFMatPrimaSubcategActionPerformed

    private void labelButtCargarElementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtCargarElementoMouseClicked
        // TODO add your handling code here:
        labelButtCargarElemento.setForeground(new java.awt.Color(23, 132, 21));
        String categoria = this.textFMatPrimaCateg.getText().toLowerCase();
        String subcategoria = this.textFMatPrimaSubcateg.getText().toLowerCase();
        String marca = this.textFMatPrimaMarca.getText().toLowerCase();
        String tipo = this.textFMatPrimaTipo.getText().toLowerCase();
        String cantidad = this.textFMatPrimaCantid.getText().toLowerCase();
        int indexcombobox = this.comboBoxUnidades.getSelectedIndex();
        String unidades = this.comboBoxUnidades.getItemAt(indexcombobox).toLowerCase(); 
        String producto = cantidad+" "+unidades+"   "+categoria.toUpperCase()+" "+subcategoria.toUpperCase()+" "+marca.toUpperCase()+" "+tipo.toUpperCase();
        listaOrdenCompra.add(producto);
        agregarAlListado();                
        labelButtCargarElemento.setForeground(new java.awt.Color(25, 118, 211));
    }//GEN-LAST:event_labelButtCargarElementoMouseClicked

    private void labelButtBorrarElementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtBorrarElementoMouseClicked
        // TODO add your handling code here:
        eliminarDelListado();
        
    }//GEN-LAST:event_labelButtBorrarElementoMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel card1CentralPanelContent;
    private javax.swing.JPanel card1CentralPanelContent1;
    private javax.swing.JPanel cardPanelMainMenu;
    private javax.swing.JPanel cardPanelNvaOrdC1;
    private javax.swing.JComboBox<String> comboBoxUnidades;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelButtBorrarElemento;
    private javax.swing.JLabel labelButtCargarElemento;
    private javax.swing.JLabel labelMatPrimaCantid;
    private javax.swing.JLabel labelMatPrimaCateg;
    private javax.swing.JLabel labelMatPrimaMarca;
    private javax.swing.JLabel labelMatPrimaSubcateg;
    private javax.swing.JLabel labelMatPrimaTipo;
    private javax.swing.JLabel labelMatPrimaUnidades;
    private javax.swing.JScrollPane listOrdenCompra;
    private javax.swing.JPanel panelListOrdCompra;
    private javax.swing.JTextField textFMatPrimaCantid;
    private javax.swing.JTextField textFMatPrimaCateg;
    private javax.swing.JTextField textFMatPrimaMarca;
    private javax.swing.JTextField textFMatPrimaSubcateg;
    private javax.swing.JTextField textFMatPrimaTipo;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtButtBajaStock;
    private javax.swing.JLabel txtButtConsInvent;
    private javax.swing.JLabel txtButtNuevoPedido;
    private javax.swing.JLabel txtButtNvaOrdenC;
    private javax.swing.JLabel txtButtToMainMenu;
    private javax.swing.JLabel txtIconNextArrow;
    private javax.swing.JLabel txtPathOrdCDetalles;
    private javax.swing.JLabel txtSubtitleConfirmarCompra;
    private javax.swing.JLabel txtSubtitleDetalleProduct;
    private javax.swing.JLabel txtSubtitleGenPDF;
    private javax.swing.JLabel txtSubtitleObservaciones;
    private javax.swing.JLabel txtTitleOrdCompra;
    // End of variables declaration//GEN-END:variables

    private void agregarAlListado() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultListModel datos = new DefaultListModel();
        for (int i = 0; i < listaOrdenCompra.size(); i++) {
            String nombre = listaOrdenCompra.get(i);
            datos.addElement(nombre);
        }
        this.jList2.setModel(datos);
    }

    private void eliminarDelListado() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultListModel model = (DefaultListModel) jList2.getModel();
        int selectedIndex = jList2.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
            listaOrdenCompra.remove(selectedIndex);
            jList2.setModel(model);
        }
    }
}
